# Generated by Django 6.0.3 on 2026-06-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_wishlist"),
        ("core", "0006_orderitem"),
    ]

    operations = []
