# Generated by Django 6.0.3 on 2026-06-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
