# Generated by Django 6.0.3 on 2026-06-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_order_is_paid_order_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name_en"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.RenameField(
            model_name="category",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="name_en",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_name",
            new_name="product_name_en",
        ),
        migrations.AddField(
            model_name="category",
            name="description_hi",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="category",
            name="name_hi",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="description_hi",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="product_name_hi",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
